### ISSUE TITLE
I am use this theme if work on tab and mobile but try to use in android TV is not work app automatically close 

### ISSUE THREAD

**Issue by vikasshinde448** [applm/ma-components#30]
I am use this theme if work on tab and mobile but try to use in android TV is not work app automatically close

**Comment by vikasshinde448** [comment]
In xml page design it give some render error

java.lang.NullPointerException   at it.moondroid.coverflow.components.ui.containers.FeatureCoverFlow.dispatchDraw(FeatureCoverFlow.java:471)   at android.view.View.draw_Original(View.java:20075)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:19849)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)   at android.view.View.draw_Original(View.java:20075)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:19849)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)   at android.view.View.draw_Original(View.java:20075)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:19849)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)   at android.view.View.draw_Original(View.java:20075)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:19849)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)   at android.view.View.draw_Original(View.java:20075)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:19849)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)   at android.view.View.draw_Original(View.java:20075)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:19849)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)   at android.view.View.draw_Original(View.java:20075)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:19849)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)   at android.view.View.draw_Original(View.java:20210)   at android.view.View_Delegate.draw(View_Delegate.java:56)   at android.view.View.draw(View.java:20177) Copy stack to clipboard
